# -*- coding: utf-8 -*-
"""pothole detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgI3pBnHfvau7qkhkWplkgOXdYyULrXW
"""

!pip install ultralytics --upgrade

from google.colab import drive
drive.mount('/content/drive')

# Copy file from Drive to Colab
!cp "/content/drive/MyDrive/pothole.zip" "/content/"

# Unzip the file
import zipfile
with zipfile.ZipFile("/content/pothole.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/")

!ls /content

from ultralytics import YOLO
model=YOLO("yolov8n.pt")
train_results=model.train(
    data="/content/data.yaml",
    epochs=20,
    imgsz=640,
    device=0
)

!ls /content/runs/detect/train/weights #to check where is the model in train 8 (mostly saved in best.pt)

from google.colab import files
uploaded = files.upload()

#IMAGE PREDICTION
from ultralytics import YOLO
# Load trained model
model = YOLO(" /content/runs/detect/train/weights/best.pt")
# Run prediction on image on your desktop saved as bcd.jpg
results = model. predict ("pothole2.jpg", conf=0.5, save=True)
print("model running done")

import os
from IPython.display import Image, display
                                                      #IMAGE PREDICTION DISPLAY(BOUNDING BOXES)
# Path to the YOLO output folder
output_dir = "runs/detect/predict10"

# List and sort output files
output_files = sorted(os.listdir(output_dir))

# Pick the most recent output image
last_output_image = os.path.join(output_dir, output_files[-1])

# Display it in Colab
display(Image(filename=last_output_image))

